export const getAllListsRoute = () => '/lists/mine'
export const getPublicListsRoute = () => '/lists/public'
export const getSettingsRoute = () => '/settings'
export const getListPage = () => '/lists/:listId'
export const getRankingPage = () => '/lists:listId/ranking'
export const getSignInPage = () => '/signin'
export const getSignUpPage = () => '/signup'
export const getSignOutPage = () => '/signout'
